### ISSUE TITLE
Suggestion: option to enable auto fix for specific linters

### ISSUE THREAD

**Issue by codeman1o1** [wearerequired/lint-action#426]
Some linters do not support auto fix, maybe this will be a fix

Something like:
black_auto_fix: true

**Comment by ocean90** [comment]
Sounds like a good idea. I'd probably keep the global `auto_fix` setting and then allow to deactivate the fixer for specific linters via `<linter>_auto_fix: false`.

**Comment by phamelink** [comment]
Hi @ocean90 , @bastienFaivre and I are students currently studying [DevOps at KTH](https://github.com/KTH/devops-course). One of our assignments is to contribute to an open-source project related to DevOps, and as big linter fans we found your action to be a perfect fit! We plan on making a pull request within the next 10 days to add this feature!

We'll follow on what you said to keep the global `auto_fix` setting and add make sure to add the inputs `<linter>_auto_fix` with a default set to true, so that when we loop over each linter, we only commit changes when both `auto_fix` and `<linter>_auto_fix` are set to true. We would add in the description of each input that if set to true, it will only auto-fix a specific linter if the global `auto_fix` is set to true to avoid any confusion for users.

We'll also suggest an addition to the README to mention this new feature. 

With regards to writing tests, since this is a rather simple feature to add, is there anything in particular you would want us to add ? 

Let us know if you any comments/suggestions!

**Comment by codeman1o1** [comment]
I demand that you remove the "stale" label
