### ISSUE TITLE
Add TypeScript support (tslint)

### ISSUE THREAD

**Issue by mCzolko** [wearerequired/lint-action#78]
We nice work! Keep it up. Would tslint be a good fit for the linters?

**Comment by ocean90** [comment]
Hi @mCzolko, thanks!

Since [TSLint is deprecated](https://github.com/palantir/tslint/issues/4534) I'd say no. You should switch to ESLint which also supports Typescript, see [this test](https://github.com/samuelmeuli/lint-action/tree/master/test/linters/projects/eslint-typescript) for an example. Is there a specific reason why you need TSLint?

**Comment by mCzolko** [comment]
Oh no, I didn't know that it will be deprecated, sorry, I should switch in my project away from TSLint. Thanks!

**Comment by Michael-Ziluck** [comment]
@ocean90 It is "deprecated". I use quotes because it is still used out of the box by Angular which is certainly not an edge case. There are definitely more Angular users than golint users.
