### ISSUE TITLE
make it possible to start a linter with npm run command from package.json

### ISSUE THREAD

**Issue by timomayer** [wearerequired/lint-action#87]
Most js projects have configured linters in package.json as npm run script to pass on arguments to eslint and start it for example with npm run lint:eslint.

Suggestion: make it possible to run a linter unsing this npm run configuration, otherwise you have to maintain paraleters for all linters in two locations: package.json and github action file.

**Comment by ocean90** [comment]
Hi there, sounds like an interesting idea but not sure how this can be implemented since some linters require specific arguments which are usually not defined in your run scripts. Some examples:

https://github.com/wearerequired/lint-action/blob/1e9f3f05412d02083a04b6ba62fe6fa905f5816e/src/linters/eslint.js#L49
https://github.com/wearerequired/lint-action/blob/1e9f3f05412d02083a04b6ba62fe6fa905f5816e/src/linters/prettier.js#L48
https://github.com/wearerequired/lint-action/blob/1e9f3f05412d02083a04b6ba62fe6fa905f5816e/src/linters/stylelint.js#L49
https://github.com/wearerequired/lint-action/blob/1e9f3f05412d02083a04b6ba62fe6fa905f5816e/src/linters/php-codesniffer.js#L48

Do you have any suggestions for a possible implementation?

**Comment by vpillinger** [comment]
@ocean90 NPM and Yarn both forward command line arguments to their underlying scripts.

Therefore, the following are equivalent.

**Current**
```--ext ${extensionsArg} ${fixArg} --no-color --format json ${args} "."```


**Updated**
package.json
```
scripts: {
  "lint": "eslint" 
}
```
```
npm run lint --ext ${extensionsArg} ${fixArg} --no-color --format json ${args} "."
OR
yarn run lint --ext ${extensionsArg} ${fixArg} --no-color --format json ${args} "."
```
